#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"; PHASE="$2"

_env=$(dokku volume:env "$APP")

if [[ $? -eq 0 ]] && [[ "$PHASE" != "build" ]]; then
  echo "$STDIN $_env"
else
  echo "$STDIN"
fi
